language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=yokadi --omit="yokadi/tests/*" yokadi/tests/tests.py
after_success:
  coveralls
notifications:
  email: false
  irc: "chat.freenode.net#yokadi"
